### ISSUE TITLE
Autoscan ignoring most changes

### ISSUE THREAD

**Issue by dulfbarglin** [l3uddz/plex_autoscan#103]
I'm sure this will be something obvious I'm missing but I've been futzing with this for hours now and I can't seem to figure out what I'm missing. Just upgraded and the config changed from GDRIVE to GOOGLE. Everything was working perfectly before and I just had it set to ignore a folder off root called "Move" where my unsorted stuff was. Now I've got my media folder as the only allowed path. My scan is working, and 5 or so files have been immediately scanned when I put them in, but most files I add just go to Ignored or Unwanted and I'm not sure why. I'll upload my current config. I also tried all three individual library folders listed and it worked about the same.  Why is it ignoring my changes or deeming them unwanted?
[config.json.sanitized.txt](https://github.com/l3uddz/plex_autoscan/files/3248886/config.json.sanitized.txt)

**Comment by desimaniac** [comment]
Few things: 

- `PLEX_LD_LIBRARY_PATH` is needs updating.
  - "PLEX_LD_LIBRARY_PATH": "/usr/lib/plexmediaserver/lib", 
- PLEX_SECTION_PATH_MAPPINGS 
  - Add trailing slash to not confuse fuzzy search. 
  - This section can also be be auto-generated. See https://github.com/l3uddz/plex_autoscan#plex-section-mappings
- To see what is being ignored, enable `SHOW_CACHE_LOGS`

Since this is a support issue, please go to to the discord server. As Github is for bugs.
